// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAZ8rJBd_OdsOGa9reVw_FJozVTpuhudss',
    appId: '1:918767328904:web:d976fcc87c72cb45c9893d',
    messagingSenderId: '918767328904',
    projectId: 'mosquenearme-a3c00',
    authDomain: 'mosquenearme-a3c00.firebaseapp.com',
    storageBucket: 'mosquenearme-a3c00.appspot.com',
    measurementId: 'G-0KVGJ147EX',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDp-8RSzSCJK-bvw-_W4L22dEj5iEj4JEw',
    appId: '1:918767328904:android:9c3d2fcc718db26bc9893d',
    messagingSenderId: '918767328904',
    projectId: 'mosquenearme-a3c00',
    storageBucket: 'mosquenearme-a3c00.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAA_TUBtyV7kQ3k8AzaDhF5PnwgB_mgGxM',
    appId: '1:918767328904:ios:86eee907224c1a35c9893d',
    messagingSenderId: '918767328904',
    projectId: 'mosquenearme-a3c00',
    storageBucket: 'mosquenearme-a3c00.appspot.com',
    iosClientId: '918767328904-tjaolm3dqt53fof5pudupejs6ahr5i4v.apps.googleusercontent.com',
    iosBundleId: 'com.loullah.mosquenearmePrayertime',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAA_TUBtyV7kQ3k8AzaDhF5PnwgB_mgGxM',
    appId: '1:918767328904:ios:86eee907224c1a35c9893d',
    messagingSenderId: '918767328904',
    projectId: 'mosquenearme-a3c00',
    storageBucket: 'mosquenearme-a3c00.appspot.com',
    iosClientId: '918767328904-tjaolm3dqt53fof5pudupejs6ahr5i4v.apps.googleusercontent.com',
    iosBundleId: 'com.loullah.mosquenearmePrayertime',
  );
}
